feat: support building shared libraries on z/OS
nodejs/gyp-next pull request #137
Opened 2022-02-23 19:43 UTC by alexcfyung

Allow gyp to build shared libraries such as .x file on z/OS. This is needed to enable node.js to build shared library on z/OS.

2022-03-26 00:01 UTC, Adnan897 requested changes
👍

2022-03-26 00:02 UTC, Adnan897 requested changes
Reqes change

2022-03-26 00:03 UTC, Adnan897 requested changes
Approve

2022-03-26 00:47 UTC, Adnan897 reviewed
Review changes

2022-03-26 00:48 UTC, Adnan897 approved these changes
Review changes

2022-03-26 00:53 UTC, Adnan897 reviewed
Request changes

2022-03-28 18:17 UTC, zsw007 commented
> Request changes

Hi, could you please clarify what changes are requested?

2022-03-31 11:46 UTC, ryzokuken approved these changes
RSLGTM, someone please merge if this works as intended.

2022-04-04 06:39 UTC, merged