chore: add npm support
nodejs/gyp-next pull request #146
Opened 2022-04-12 11:45 UTC by XadillaX

2022-04-13 01:59 UTC, gengjiawen commented
Actually `node-gyp` got the full clone, maybe redundant for npm package. https://github.com/nodejs/node-gyp/tree/master/gyp

2022-04-13 02:52 UTC, XadillaX commented
> Actually `node-gyp` got the full clone, maybe redundant for npm package. https://github.com/nodejs/node-gyp/tree/master/gyp

After making it an npm package, node-gyp may simply depend on it in "dependencies" field.

2022-04-13 10:49 UTC, ryzokuken approved these changes

2022-04-13 10:53 UTC, cclauss commented
@ryzokuken Why are so many tests failing?  Do we need to work on our tests?

2022-04-13 11:16 UTC, cclauss commented
What is the relationship between detect-python-interpreter and https://github.com/nodejs/node-gyp/blob/master/lib/find-python.js ?  Do they both have the same kind of [test coverage](https://github.com/nodejs/node-gyp/blob/master/.github/workflows/tests.yml#L10-L13) because gyp gets run on a lot of esoteric hardware and OSes these daze.

2022-04-13 12:36 UTC, XadillaX commented
> What is the relationship between detect-python-interpreter and [find-python.js](https://github.com/nodejs/node-gyp/blob/master/lib/find-python.js?rgh-link-date=2022-04-13T11%3A16%3A29Z) ? Do they both have the same kind of [test coverage](https://github.com/nodejs/node-gyp/blob/master/.github/workflows/tests.yml?rgh-link-date=2022-04-13T11%3A16%3A29Z#L10-L13) because gyp gets run on a lot of esoteric hardware and OSes these daze.

`detect-python-interpreter` only tests `python*` one by one and returns the first succeeded one on `python* -v`.

2022-04-13 12:38 UTC, targos commented
What issue does it solve?

2022-04-14 05:03 UTC, XadillaX commented
> What issue does it solve?

1. Projects depend on it can remove the hard copy, and use it in a `package.json`. E.g. Node.js
2. node-gyp may replace the hard copy with a dependency.

2022-04-14 06:09 UTC, targos commented
I don't know if it something that node-gyp wants, but from the Node.js perspective, it is unlikely to happen, as node needs to copy so we can build it offline from the tarball.

2022-04-14 09:45 UTC, ryzokuken commented
> @ryzokuken Why are so many tests failing? Do we need to work on our tests? Rerunning failing tests... Still fail.

Looks like changes were made to gyp in Node without properly being upstreamed here first: https://github.com/nodejs/node/issues/40735. @targos I am sympathetic to the use-case of building Node.js from a tarball but how could we keep gyp-next in the tree and avoid this from happening over and over again? Perhaps include it as a git submodule instead?

2022-04-14 10:00 UTC, targos commented
> how could we keep gyp-next in the tree and avoid this from happening over and over again?

The same question applies to all our bundled dependencies. I don't have a perfect solution, but for now reviewers should pay attention to this.
BTW, I tried to do https://github.com/nodejs/node/issues/40735 myself, but the changes are really non-trivial and I'm afraid to introduce them here and break node-gyp users.

2022-04-14 10:02 UTC, targos commented
`node-gyp integration` errors should be fixed in the node-gyp repo: `        not ok 2 - request to https://localhost:49373/ failed, reason: certificate has expired`

2022-04-14 11:41 UTC, XadillaX commented
@targos https://github.com/nodejs/node/tree/master/tools/node_modules/eslint

ESLint stays in `node_modules` and be added to repository tree. Maybe we can do it for gyp-next either?

2022-04-14 11:42 UTC, targos commented
> @targos https://github.com/nodejs/node/tree/master/tools/node_modules/eslint
> 
> ESLint stays in `node_modules` and be added to repository tree. Maybe we can do it for gyp-next either?

Maybe, but I don't see any advantage to doing so. And if we merge this, we need to manage npm releases, which is more burden for a project that has almost no maintainer.

2022-04-14 14:08 UTC, ryzokuken commented
> the changes are really non-trivial and I'm afraid to introduce them here and break node-gyp users.

fair point.

> And if we merge this, we need to manage npm releases, which is more burden for a project that has almost no maintainer.

I agree. This is the opposite of what we want, we should be instead reducing the maintenance cost of this project as much as possible.

2022-04-14 16:32 UTC, richardlau commented
I don't think this is going to make things any better for Node.js core. 

For node-gyp though it might make maintenance of node-gyp easier (albeit slightly increasing the maintenance burden here) -- at the moment there is a lot of confusion over gyp-next vs node-gyp and we frequently get PR's opened in node-gyp that are actually gyp changes that should be made here. Doing this and then making gyp-next a dependency for node-gyp would allow us to remove the gyp copy in node-gyp so the only code left there would be the Node.js wrapper.

2022-04-15 08:49 UTC, ryzokuken commented
@richardlau would we need npm for that? Couldn't that also be done with a git submodule for example?

2022-04-15 12:54 UTC, richardlau commented
> @richardlau would we need npm for that? Couldn't that also be done with a git submodule for example?

Other package managers are available 🙂. The point would be to make, from node-gyp's point of view, gyp-next the same as any other dependency node-gyp currently has. You already need to `npm install` (or your package manager's equivalent) node-gyp in order to use it or run its tests if maintaining it. We do not, for example, vendor in the tar module into node-gyp. The main reason gyp was vendored into node-gyp was that when gyp was maintained by Google it was not versioned or published to a package repository.

2022-04-15 13:56 UTC, targos commented
I won't object to this PR, but keep in mind that if we merge, someone's going to have to setup and maintain the npm release.

2022-04-15 18:32 UTC, cclauss requested changes
Sorry but I am going to object to this PR.

`detect-python-interpreter` only tells us if some version of Python 2 or 3 is installed.  It does not tell us what that version is and if that version meets our build requirements.  We do not need additional support requests from users who are attempting to build with legacy Python.

Also, let's fix the tests before approving a bunch more PRs with failing tests.

2024-06-17 22:37 UTC, cclauss commented
Closing.  This repo is all Python code and no JavaScript code.  The code is released into PyPI which is the Python equivalent of npm.  https://github.com/nodejs/gyp-next/blob/main/README.md

2024-06-17 22:37 UTC, closed without merging