Fix PLR1714 lint errors
nodejs/gyp-next pull request #202
Opened 2023-07-29 02:37 UTC by rzhao271

2023-07-30 05:37 UTC, cclauss commented
Please adjust https://github.com/nodejs/gyp-next/blob/main/pyproject.toml#L38 to make these changes permanent.

2023-07-31 05:25 UTC, cclauss approved these changes

2023-07-31 05:30 UTC, cclauss commented
@rzhao271 The `ruff rule PLR1714` above makes it simple to make you commit message self-documenting for those who do not have all rules mesmerized.  Especially helpful for project maintainers is the `Why is this bad?` section.

2023-07-31 05:38 UTC, cclauss requested changes

2023-07-31 05:38 UTC, cclauss commented on pyproject.toml
> +  "PLR",  # Pylint
`PL` includes all of `PLC`, `PLE`, `PLR`, and `PLW` so this change can be reverted.

2023-08-11 18:29 UTC, rzhao271 commented
@cclauss can the CI be restarted? The integration tests had an issue with finding the tarballs.

2023-08-26 00:12 UTC, cclauss approved these changes

2023-08-26 00:12 UTC, merged